defaults:
  - override /trainer_cfg@_global_: base_trainer
  - override /model_cfg@_global_: qwen3_5/qwen3_5_9b
  - override /data_cfg@_global_: fineweb_edu_shuffled
  - _self_

custom_class: custom_models.drope.DroPEQwen3_5ForCausalLM
from_pretrained: true
drope: true

model_custom_config:
  _target_: custom_models.drope.DroPEQwen3_5Config.from_pretrained
  pretrained_model_name_or_path: ${model_name_or_path}
  attention_type: nope

train_batch_size: 512
per_device_train_batch_size: 1
max_seq_length: 32768
max_steps: 5000
learning_rate: 1e-4
save_steps: 100
lr_scheduler_type: cosine

underdeep_project: drope-qwen3-5
underdeep_run_name: ${trainer_log_name}_${model_log_name}_${max_steps}steps_bs${train_batch_size}_lr${learning_rate}

trainer_args:
  warmup_steps: 100
