custom_class: null
from_pretrained: false
drope: false
memory_efficient_ce: ${memory_efficient_ce}

loaded_model:
  _target_: hydra_utils.load_model
  model_args: ${model_args}
  trust_remote_code: ${model_trust_remote_code}
  config: ${model_custom_config}
  custom_class: ${custom_class}
  from_pretrained: ${from_pretrained}
  drope: ${drope}
  memory_efficient_ce: ${memory_efficient_ce}
